export const config = {
  env: process.env.NODE_ENV || 'production',
  port: parseInt(process.env.PORT || '3000', 10),
  host: process.env.HOST || '0.0.0.0',
  requestTimeoutMs: parseInt(process.env.REQUEST_TIMEOUT_MS || '300000', 10),
  maxRequestSizeBytes: parseInt(process.env.MAX_REQUEST_SIZE_BYTES || '1048576', 10),
  apiKey: process.env.API_KEY || 'default-api-key-change-in-production',
  corsOrigin: process.env.CORS_ORIGIN || '*',
  youTubeDlPath: process.env.YOUTUBE_DL_PATH || '/usr/local/bin/yt-dlp',
  ffmpegPath: process.env.FFMPEG_PATH || '/usr/local/bin/ffmpeg',
  conversionTimeoutMs: parseInt(process.env.CONVERSION_TIMEOUT_MS || '300000', 10),
  maxDurationSeconds: parseInt(process.env.MAX_DURATION_SECONDS || '3600', 10),
  queueMaxSize: parseInt(process.env.QUEUE_MAX_SIZE || '1000', 10),
  tempDir: process.env.TEMP_DIR || '/tmp/yt-mp3',
  outputDir: process.env.OUTPUT_DIR || '/storage/mp3s',
  cleanupIntervalMs: parseInt(process.env.CLEANUP_INTERVAL_MS || '3600000', 10),
  fileRetentionHours: parseInt(process.env.FILE_RETENTION_HOURS || '24', 10),
  redisUrl: process.env.REDIS_URL || null,
  cacheTtlSeconds: parseInt(process.env.CACHE_TTL_SECONDS || '3600', 10),
  logLevel: process.env.LOG_LEVEL || 'info',
  auditLogPath: process.env.AUDIT_LOG_PATH || '/var/log/yt-mp3-audit.log',
  enableMetrics: process.env.ENABLE_METRICS === 'true',
  metricsPort: parseInt(process.env.METRICS_PORT || '9090', 10),
  maxRequestsPerIpHour: parseInt(process.env.MAX_REQUESTS_PER_IP_HOUR || '50', 10),
  maxRequestsPerKeyHour: parseInt(process.env.MAX_REQUESTS_PER_KEY_HOUR || '500', 10),
  banThreshold: parseInt(process.env.BAN_THRESHOLD || '10', 10),
  banDurationMs: parseInt(process.env.BAN_DURATION_MS || '3600000', 10),
  circuitBreakerThreshold: parseInt(process.env.CIRCUIT_BREAKER_THRESHOLD || '5', 10),
  circuitBreakerTimeoutMs: parseInt(process.env.CIRCUIT_BREAKER_TIMEOUT_MS || '60000', 10),
};
